export const CREATE_CONSULTA = "CREATE_CONSULTA";

export const RETRIEVE_CONSULTAS = "RETRIEVE_CONSULTAS";

export const UPDATE_CONSULTA = "UPDATE_CONSULTA";

export const DELETE_CONSULTA = "DELETE_CONSULTA";