export const CREATE_ESPECIALIDADE = "CREATE_ESPECIALIDADE";

export const RETRIEVE_ESPECIALIDADES = "RETRIEVE_ESPECIALIDADES";

export const UPDATE_ESPECIALIDADE = "UPDATE_ESPECIALIDADE";

export const DELETE_ESPECIALIDADE = "DELETE_ESPECIALIDADE";