export const CREATE_HARDWARE = "CREATE_HARDWARE";

export const RETRIEVE_HARDWARES = "RETRIEVE_HARDWARES";

export const UPDATE_HARDWARE = "UPDATE_HARDWARE";

export const DELETE_HARDWARE = "DELETE_HARDWARE";