export const CREATE_SEGURADO = "CREATE_SEGURADO";

export const RETRIEVE_SEGURADOS = "RETRIEVE_SEGURADOS";

export const UPDATE_SEGURADO = "UPDATE_SEGURADO";

export const DELETE_SEGURADO = "DELETE_SEGURADO";