export const CREATE_AGENCIA = "CREATE_AGENCIA";

export const RETRIEVE_AGENCIAS = "RETRIEVE_AGENCIAS";

export const UPDATE_AGENCIA = "UPDATE_AGENCIA";

export const DELETE_AGENCIA = "DELETE_AGENCIA";