export const CREATE_DEPARTAMENTO = "CREATE_DEPARTAMENTO";

export const RETRIEVE_DEPARTAMENTOS = "RETRIEVE_DEPARTAMENTOS";

export const UPDATE_DEPARTAMENTO = "UPDATE_DEPARTAMENTO";

export const DELETE_DEPARTAMENTO = "DELETE_DEPARTAMENTO";